[loggers]
keys=root,litellm

[handlers]
keys=console

[formatters]
keys=default

[formatter_default]
class=colorlog.ColoredFormatter
format=%(yellow)s%(asctime)s%(reset)s|%(purple)s%(module)s.%(funcName)s:L%(lineno)s%(reset)s|%(log_color)s%(levelname)s%(reset)s %(message)s

[handler_console]
class=logging.StreamHandler
formatter=default
level=INFO

[logger_root]
level=INFO
handlers=console
propagate=0

[logger_litellm]
level=WARNING
handlers=console
qualname=LiteLLM
propagate=0
